name: Hot Search Monitor

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run scraper
        env:
          MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: |
          python main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hot_data
          force_orphan: true
    
