name: Test Workflow

on:
  push:
    branches: [main]  # 触发分支
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 */2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        env:
          MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: |
          python main.py
    
